name: macOS

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev/*

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build macOS
      run: ./make.sh all
